name: Node CI

on:
  push:
    branches:
      - master # default branch

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn bootstrap --npm-client yarn
      - run: yarn build
      - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                # github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs-dist

